server:
  port: 8089
  servlet:
    session:
      cookie:
        name: sessionid_merchant
spring:
  datasource:
    url: jdbc:mysql://66.112.219.47:3306/runscore2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 19880806Ww*
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 30
      maximum-pool-size: 10
      max-lifetime: 300000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 66.112.219.47
    #    host: 47.92.167.103
    password: 19880806
  session:
    store-type: redis
    timeout: 7200s
redisson:
  singleServerConfig:
    address: 66.112.219.47:6379
    password: 19880806
#jetcache:
#  areaInCacheName: false
#  local:
#    default:
#      type: linkedhashmap
#      keyConvertor: fastjson
#  remote:
#    default:
#      type: redis.lettuce
#      keyConvertor: fastjson
#      uri: redis://127.0.0.1:6379/
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 66.112.219.47
      port: 6379
      password: 19880806
      database: 0
      timeout: 10000
