server:
  port: 8090
  servlet:
    session:
      cookie:
        name: sessionid_mobile
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runscore2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
#    password: root
    password: 19880806
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 15
      max-lifetime: 500000
      connection-test-query: SELECT 1
      auto-commit: true
      connection-timeout: 60000
    test-on-borrow: true
    test-while-idle: true
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: 
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 127.0.0.1
#    host: 47.92.167.103
    password: 19880806
  session:
    store-type: redis
    timeout: 7200s
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
redisson:
  singleServerConfig:
    address: 127.0.0.1:6379
    password: 19880806
#jetcache:
#  areaInCacheName: false
#  local:
#    default:
#      type: linkedhashmap
#      keyConvertor: fastjson
#  remote:
#    default:
#      type: redis.lettuce
#      keyConvertor: fastjson
#      uri: redis://127.0.0.1:6379/
##      uri: redis://47.92.167.103:6379/
##      uri: redis://X6FJCFYEndFzX6FJCFYEndFz@47.101.49.12:6379/
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
      password: 19880806
      database: 0
      timeout: 10000